sudo: false
before_script:
  - composer self
  - composer --version
  - composer install -n
language: php
php:
  - '7.2'
  - '7.3'
before_install:
  - pecl channel-update pecl.php.net
  - printf "\n" | pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
addons:
  apt:
    packages:
      - libyaml-dev
script:
  - php vendor/bin/phpcs --standard=psr2 src/ -n
  - composer test -- --coverage-clover=coverage.xml
after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)

#after_failure:

# Monitor only these branches
branches:
  only:
    - master
    - dev

# You can delete the cache using travis-ci web interface
cache:
  directories:
    - $HOME/.composer/cache